# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Release on Windows

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.RADARSIMC }}
        submodules: true
    - name: Build
      run: |
        .\build_win.bat
    - name: Archive built module
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: radarsimlib_win
        path: .\radarsimlib
