name: Build Freetier Library on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RADARSIMCPP }}
          submodules: recursive
      - name: Build
        run: |
          .\build.bat --arch cpu --tier free
      - name: Archive built module
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: radarsimlib_win_x86_64_cpu_free
          path: .\radarsimlib_win_x86_64_cpu_free
